apiVersion: "serving.knative.dev/v1"
kind: "Service"
metadata:
  name: "collector"
  annotations:
    run.googleapis.com/launch-stage: "BETA"
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "2"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 120
      containers:
      - image: "gcr.io/alter-rebbe-2/collector"
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
#           MaxHeapSize is never less than 126Mb, so "ergonomic" 1/4 starts at 512Mi:
            memory: "512Mi"
#        env:
#        - name: "JAVA_TOOL_OPTIONS"
#          value: "-XX:+PrintFlagsFinal"
