name: "Branch CI"
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the code"
        uses: actions/checkout@master

      - name: "Set up Java"
        uses: actions/setup-java@master
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: "Build and test"
        run: ./gradlew --no-daemon build
